elasticsearch:
  timezone: Asia/Seoul
  hosts:
    es-server:
      host: 192.168.0.2

# TODO support fritzing-parts-api-client-js
hardware:
  sensors:
    dht:
      pins:
        - 11
      nature:
        - temperature
        - humidity

    light:
      pins:
        - 2
      nature:
        - light

  motors:
