version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - pi-groot

  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.0
    networks:
      - pi-groot
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - pi-groot

networks:
  pi-groot: